GET http://localhost:3000/books

###
GET http://localhost:3000/books/3

###
POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "Test",
  "price": "10",
  "author_id": "7"
}

###
PUT http://localhost:3000/books/5
Content-Type: application/json

{
  "name": "Test",
  "price": "2",
  "author_id": "3"
}

###
DELETE http://localhost:3000/books/3
